### ISSUE TITLE
How Can I Run IOS app, I did not find .xcodeproj file in sample projects

### ISSUE THREAD

**Issue by Moozart** [Tlaster/PreCompose#104]
Hello,
Thanks a lot for this amazing project.
How Can I Run IOS app, I did not find .xcodeproj file in sample projects. 
I investigated this repo, "[compose-multiplatform-ios-android-template](https://github.com/JetBrains/compose-multiplatform-ios-android-template)"
Is it different approach from urs?

**Comment by Tlaster** [comment]
PreCompose sample still using "old" Compose iOS project structure, so you'll need to run `./gradlew :sample:todo:ios:iosDeploySimulatorDebug` in order to run sample iOS project.
I do have a plan on upgrading to new Compose iOS project structure, but currently I do not have the time to do that, but PreCompose's setup should be not that different for iOS.

**Comment by Moozart** [comment]
Thank you so much, I am trying to implement with new IOS project structure. 
I just faced " java.lang.IllegalStateException: No StateHolder provided" exception running on Android

**Comment by Moozart** [comment]
Sorry my fault, I replaced setContent with "moe.tlaster.precompose.lifecycle.setContent".
