### ISSUE TITLE
Crash when specifying arguments in a group navigation initialRoute

### ISSUE THREAD

**Issue by Lavmee** [Tlaster/PreCompose#184]
If we specify arguments in the initialRoute in a group, we get the error "Initial route /nested/1 not found".

Sample:
```kotlin
@Composable
fun AppNavigation() {
    val navigator = rememberNavigator()
    NavHost(
        initialRoute = "/group",
        navigator = navigator,
        modifier = Modifier.fillMaxSize()
    ) {
        group(
            route = "/group",
            initialRoute = "/nested/1",
        ) {
            scene(
                route = "/nested/{id}"
            ) {
            }
        }
    }
}
```

**Comment by Tlaster** [comment]
Seems like the check [here](https://github.com/Tlaster/PreCompose/blob/18eb66a11beb6ca486fcdf1af667182b1dbfbfa1/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt#L71) is not necessary, I'm working on a fix.

**Comment by Tlaster** [comment]
While working on a fix, I was wondering: should this be a bug?
Since currently group support nesting, so we can easily have something like:
```Kotlin
group(route = "/group", initialRoute = "/nested/1") {
    group(route = "/nested/{id}", initialRoute = "/innternested/2") {
        scene(
            route = "/innternested/{id}"
        ) {
        }
        // ...
    }
}
```
And this might lead to misunderstanding and confusion: which id I'm getting? and how to get group's id?
So I would like to keep the group as simple as possible, remove the support of pattern matching for both the `route` and `initialRoute` parameter, what do you think?

**Comment by sureshmaidaragi1919** [comment]
@Lavmee did you tried to make path variable as optional by ?
